Sync from parachain solidity assertions
litentry/DynamicAssertion pull request #5
Opened 2024-09-18 05:05 UTC by higherordertech

2024-09-18 07:21 UTC, 0xverin approved these changes

2024-09-18 09:19 UTC, BillyWooo requested changes
@higherordertech @0xverin can you take a look why CI failed?

2024-09-24 02:18 UTC, 0xverin commented
> @higherordertech @0xverin can you take a look why CI failed?

fixed it in this PR.
https://github.com/litentry/litentry-parachain/pull/3072

2024-09-24 06:10 UTC, BillyWooo approved these changes

2024-09-24 06:10 UTC, merged